import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const catalogue=read('catalogue/items.json');
const UUID={};
for(const [ref,item] of Object.entries(catalogue)){
 assert(/^(skill|talent|trait|gear|prayer)\.[A-Za-z][A-Za-z0-9]*$/.test(ref),`Invalid catalogue key: ${ref}`);
 assert(/^Compendium\.[\w-]+\.[\w-]+\.Item\.[A-Za-z0-9]+$/.test(item.uuid),`Invalid UUID: ${ref}`);
 assert.equal(item.requires,item.uuid.split('.')[1],`Incorrect dependency: ${ref}`);
 const [group,key]=ref.split('.');(UUID[group]??={})[key]=item.uuid;
}
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(dir,e.name)):e.name.endsWith('.json')?[path.join(dir,e.name)]:[]).sort();}
const ids=new Set();
const allowed=new Set(['id','folder','name','type','species','stats','wounds','skills','items']);
const characteristics=['ws','bs','s','t','i','ag','dex','int','wp','fel'];
const profiles=files(path.join(root,'actors')).map(file=>{
 const actor=JSON.parse(fs.readFileSync(file,'utf8'));
 for(const key of Object.keys(actor))assert(allowed.has(key),`${file}: unknown field ${key}`);
 assert(/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(actor.id),`${file}: invalid ID`);
 assert(!ids.has(actor.id),`Duplicate ID: ${actor.id}`);ids.add(actor.id);
 assert.equal(path.basename(file),`${actor.id}.json`);
 for(const key of ['folder','name','species'])assert(typeof actor[key]==='string'&&actor[key].trim(),`${actor.id}: missing ${key}`);
 assert(['npc','creature'].includes(actor.type),`${actor.id}: invalid type`);
 assert.deepEqual(Object.keys(actor.stats).sort(),['m',...characteristics].sort(),`${actor.id}: incorrect stats fields`);
 for(const value of Object.values(actor.stats))assert(Number.isInteger(value)&&value>=0,`${actor.id}: invalid stat`);
 if('wounds' in actor)assert(Number.isInteger(actor.wounds)&&actor.wounds>0,`${actor.id}: invalid printed Wounds`);
 assert(Array.isArray(actor.skills)&&Array.isArray(actor.items),`${actor.id}: skills and items must be arrays`);
 assert(!(actor.items.some(i=>i.ref==='gear.spear'&&i.equipped)&&actor.items.some(i=>i.ref==='gear.shield'&&i.equipped)),`${actor.id}: two-handed spear cannot be equipped with a shield`);
 function resolve(entry,skill){
  assert(catalogue[entry.ref],`${actor.id}: missing reference ${entry.ref}`);
  const keys=skill?['ref','total','characteristic','name']:['ref','name','specification','quantity','worn','equipped','loaded','ugly','damage','ammoRef'];
  for(const key of Object.keys(entry))assert(keys.includes(key),`${actor.id}: unsupported entry field ${key}`);
  if(skill){
   assert(entry.ref.startsWith('skill.'),`${actor.id}: wrong skill reference`);
   assert(characteristics.includes(entry.characteristic),`${actor.id}: invalid skill characteristic`);
   assert(Number.isInteger(entry.total)&&entry.total>=actor.stats[entry.characteristic],`${actor.id}: invalid skill total`);
  }else{
   assert(!entry.ref.startsWith('skill.'),`${actor.id}: put skills in skills array`);
   for(const key of ['equipped','worn','loaded','ugly'])if(key in entry)assert(typeof entry[key]==='boolean',`${actor.id}: ${key} must be boolean`);
   if('quantity' in entry)assert(Number.isInteger(entry.quantity)&&entry.quantity>=0,`${actor.id}: invalid quantity`);
   if('damage' in entry)assert(typeof entry.damage==='string'&&/^(SB\+\d+|\+\d+)$/.test(entry.damage),`${actor.id}: invalid damage`);
   if(entry.ref==='trait.venom')assert(/^[+-]?\d+$/.test(entry.specification??''),`${actor.id}: Venom requires numeric strength`);
   if('ammoRef' in entry)assert(entry.ref.startsWith('gear.')&&catalogue[entry.ammoRef]&&actor.items.some(i=>i.ref===entry.ammoRef),`${actor.id}: ammunition must be present in inventory`);
  }
  const {ref,ammoRef,...options}=entry;
  return {uuid:catalogue[ref].uuid,...options,...(ammoRef?{ammoUuid:catalogue[ammoRef].uuid}:{})};
 }
 for(const group of [actor.skills,actor.items])assert.equal(new Set(group.map(e=>`${e.ref}|${e.specification??''}|${e.name??''}`)).size,group.length,`${actor.id}: duplicate item reference`);
 return {...actor,skills:actor.skills.map(e=>resolve(e,true)),items:actor.items.map(e=>resolve(e,false))};
});
const content='// Generated by npm run build. Edit actors/ and catalogue/ instead.\n'+
 'export const MODULE_ID = "wfrp4e-quick-npc-library";\n'+
 'export const ROOT_FOLDER = "WFRP4e Quick NPC Library";\n'+
 `export const UUID = ${JSON.stringify(UUID,null,2)};\n`+
 `export const PROFILES = ${JSON.stringify(profiles,null,2)};\n`;
const output=path.join(root,'module/scripts/data.js');
if(process.argv.includes('--check'))assert.equal(fs.readFileSync(output,'utf8'),content,'Generated data is stale. Run npm run build.');
else fs.writeFileSync(output,content);
console.log(`Validated ${profiles.length} actors and ${Object.keys(catalogue).length} item references.`);
